export const CHECK_USER = "CHECK_USER"
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS"
export const CHECK_USER_FAILURE = "CHECK_USER_FAILURE"

export const USER_SIGN_IN = "USER_SIGN_IN"
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS"
export const USER_SIGN_IN_FAILURE = "USER_SIGN_IN_FAILURE"

export const USER_SIGN_OUT = "USER_SIGN_OUT"
export const USER_SIGN_OUT_SUCCESS = "USER_SIGN_OUT_SUCCESS"
export const USER_SIGN_OUT_FAILURE = "USER_SIGN_OUT_FAILURE"

export const USER_SIGN_UP = "USER_SIGN_UP"
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS"
export const USER_SIGN_UP_FAILURE = "USER_SIGN_UP_FAILURE"

export const USER_CONFIRM_SIGN_IN = "USER_CONFIRM_SIGN_IN"
export const USER_CONFIRM_SIGN_IN_SUCCESS = "USER_CONFIRM_SIGN_IN_SUCCESS"
export const USER_CONFIRM_SIGN_IN_FAILURE = "USER_CONFIRM_SIGN_IN_FAILURE"

export const USER_CONFIRM_SIGN_UP = "USER_CONFIRM_SIGN_UP"
export const USER_CONFIRM_SIGN_UP_SUCCESS = "USER_CONFIRM_SIGN_UP_SUCCESS"
export const USER_CONFIRM_SIGN_UP_FAILURE = "USER_CONFIRM_SIGN_UP_FAILURE"

export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD"
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS"
export const USER_FORGOT_PASSWORD_FAILURE = "USER_FORGOT_PASSWORD_FAILURE"

export const USER_FORGOT_PASSWORD_RESET = "USER_FORGOT_PASSWORD_RESET"
export const USER_FORGOT_PASSWORD_RESET_SUCCESS = "USER_FORGOT_PASSWORD_RESET_SUCCESS"
export const USER_FORGOT_PASSWORD_RESET_FAILURE = "USER_FORGOT_PASSWORD_RESET_FAILURE"

export const USER_VERIFY_CONTACT = "USER_VERIFY_CONTACT"
export const USER_VERIFY_CONTACT_SUCCESS = "USER_VERIFY_CONTACT_SUCCESS"
export const USER_VERIFY_CONTACT_FAILURE = "USER_VERIFY_CONTACT_FAILURE"

export const CHANGE_SCREEN = "CHANGE_SCREEN"