// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0e0fc721-f20c-4844-84e0-fa52cb02f931",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TXAnI80zS",
    "aws_user_pools_web_client_id": "7c41oa7milia0nqpt3i6l04jo"
}


export default awsmobile
